---
- name: Converge
  hosts: all
  tasks:
    - name: create dir /run/sshd
      file: path=/run/sshd state=directory
      mode: '0644'
    - name: "Include 1mr.openssh"
      include_role:
        name: "1mr.openssh"
